# .travis.yml - travis CI config for github

sudo: required
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get -qq update
  - pip install lbry-libtorrent
install: true
script: python3 -m pytest
