# .travis.yml - travis CI config for github

language: python
python:
  - "3.4"
  - "3.5"
  - "nightly"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-libtorrent
install: true
script: python3 test.py
