# .travis.yml - travis CI config for github

sudo: required
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-libtorrent
install: true
script: python3 -m pytest test.py
